name: Plugin CI

on:
  workflow_call:
    inputs:
      lint:
        description: 'Set to true to run linting scripts.'
        required: false
        default: false
        type: boolean
      lint-script:
        description: 'Customize the lint script name.'
        required: false
        default: 'lint'
        type: string
      test-script:
        description: 'Customize the test script name.'
        required: false
        default: 'test'
        type: string
      node-matrix:
        description: 'Customize the node matrix.'
        required: false
        default: '[10, 12, 14, 16]'
        type: string

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Skip lint
        if: ${{ inputs.lint == false}}
        run: exit 0
      - uses: actions/checkout@v2
        if: ${{ inputs.lint == true}}
      - name: Use Node.js
        if: ${{ inputs.lint == true}}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        if: ${{ inputs.lint == true}}
        run: npm i --ignore-scripts
      - name: Lint code
        if: ${{ inputs.lint == true}}
        run: npm run ${{ inputs.lint-script }}

  test:
    needs: linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ${{ fromJSON(input.node-matrix) }}
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm i --ignore-scripts
      - name: Run Tests
        run: npm run ${{ inputs.test-script }}

  automerge:
    needs: test
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
