name: Node.js current branch - Plugin CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install Dependencies
        run: npm i --ignore-scripts

      - name: Run Tests on Node.js current branch
        run: npm run test
